#!/bin/sh
# Remove all metadata from directory tree
echo "Clear directory $(realpath --relative-to=$ZCP_DATASOURCE_ROOT $(pwd))"
read -p "Continue? [y/N]" cont
[ "$cont" != "y" ] && exit 1
find -type d -name 0000-index -print -prune -exec rm -rf "{}" \;
echo
echo Done
read
