#!/usr/bin/env bash
# Copy the current directory to the FTP server

FTP_HOST=
FTP_USER=
FTP_PASS=
FTP_ROOT=/

FTP_CONFIG="$ZCP_DATASOURCE_ROOT"/0000-index/ftp-server.conf

if [ ! -f "$FTP_CONFIG" ] ; then
	echo "Config file not found at $FTP_CONFIG"
	exit 1
fi

. "$FTP_CONFIG"

LCD="."
RCD="$FTP_ROOT/$(realpath --relative-to=$ZCP_DATASOURCE_ROOT $ZCP_DIRECTORY)"
DRY_RUN="--dry-run"
#DELETE="--delete"

lftp -c "set ftp:list-options -a;
set cmd:fail-exit yes;
set ssl:verify-certificate false;
open '$FTP_HOST';
login $FTP_USER $FTP_PASS;
lcd $LCD;
mkdir -p $RCD;
cd $RCD;
mirror --reverse \
       --no-perms \
       $DRY_RUN \
       $DELETE \
       --verbose"
echo
echo Done
read
